Neue Auflage für Buch von Uwe Vigenschow et al.
isaqb-org/curriculum-soft pull request #3
Opened 2024-09-09 21:46 UTC by StefanZoerner

Vom Buch "Soft Skills für Softwareentwickler" ist 2019 eine neue Auflage erschienen.

2024-09-11 06:51 UTC, programming-wolf requested changes

2024-09-11 06:51 UTC, programming-wolf commented on docs/99-references/00-references.adoc
> +- [[[vigenschow, Vigenschow+ 2019]]] Vigenschow, U., Schneider, B., Meyrose, I.: Soft Skills für Softwareentwickler: Fragetechniken, Konfliktmanagement, Kommunikationstypen und -modelle.
Sollte dann nicht auch das Jahr im Literaturverzeichnis auftauchen? Sowie auch der Verlag?

2024-09-11 13:49 UTC, programming-wolf requested changes
Noch ein paar mehr Punkte. 😬

2024-09-11 13:49 UTC, programming-wolf commented on docs/00b-basics/03-timing-didactics-and-more.adoc
> +Die genannten Zeiten sind Empfehlungen. Die Dauer einer Schulung zum Modul SOFT sollte mindestens 3 Tage betragen, kann aber länger sein. Anbieter können sich durch Dauer, Didaktik, Art und Aufbau de
Wieso habt ihr den Text hier geändert? Wollt ihr das bitte wieder rückgängig machen? 🙂 

Gerade die Variablen für den Kurznamen und der Dauer müssen da drin bleiben. 
Der neue Text unten ist einwandfrei.

2024-09-11 13:49 UTC, programming-wolf commented on docs/00b-basics/04-prerequisites-for-this-training.adoc
> +Die kommunikativen Herausforderungen von Softwarearchitekt:innen theorertisch und / oder praktisch zu kennen ist empfehlenswert.
Tippfehler: `theoretisch`

2024-09-11 13:49 UTC, programming-wolf commented on docs/00b-basics/04-prerequisites-for-this-training.adoc
> +Die kommunikativen Herausforderungen von Softwarearchitekt:innen theorertisch und / oder praktisch zu kennen ist empfehlenswert.
Ist das nicht ein bisschen sehr abstrakt/generisch? Oder wollt ihr hervorheben, dass es eigentlich keine speziellen Voraussetzungen gibt?

2024-09-11 13:49 UTC, programming-wolf commented on docs/00b-basics/06-complementary-information.adoc
> +Die Schulung geht auf die kontextüblichen Arbeitssituationen von Architekt:innen als "Nabe im Rad" konkret ein und liefert pragmatisches Handwerkszeug, um den eigenen Soft-Skills-Baukasten anzureiche
müsste das nicht `handzuhaben` heißen?

2024-09-11 13:49 UTC, programming-wolf commented on docs/00b-basics/06-complementary-information.adoc
> +Die in der Schulung „Soft Skills für Architekten“ gelernten Inhalte werden in der Prüfung zum iSAQB-CPSAA nicht geprüft. Es wird jedoch von Prüflingen erwartet, dass sie ihre Soft Skills nutzen, um d
`iSAQB® CPSA®-A`

In Asciidoc könnt ihr mit `^(R)^` das hochstellen.

2024-09-11 13:49 UTC, programming-wolf commented on docs/99-references/00-references.adoc
> +- [[[mayrshofer, Mayrshofer 2006]]] Mayrshofer, D., Kröger, H. A.: Prozesskompetenz in der Projektarbeit. 3. Auflage, Edition Windmühle 2006
Habt ihr das Buch bewusst "älter" gemacht?

2024-09-11 14:28 UTC, StefanZoerner commented on docs/99-references/00-references.adoc
> +- [[[mayrshofer, Mayrshofer 2006]]] Mayrshofer, D., Kröger, H. A.: Prozesskompetenz in der Projektarbeit. 3. Auflage, Edition Windmühle 2006
Das alte war falsch. Das gab es gar nicht.

2024-09-11 14:30 UTC, StefanZoerner commented on docs/99-references/00-references.adoc
> +- [[[vigenschow, Vigenschow+ 2019]]] Vigenschow, U., Schneider, B., Meyrose, I.: Soft Skills für Softwareentwickler: Fragetechniken, Konfliktmanagement, Kommunikationstypen und -modelle.
Ist mittlerweile drin.

2024-09-11 15:31 UTC, StefanZoerner commented on docs/00b-basics/04-prerequisites-for-this-training.adoc
> +Die kommunikativen Herausforderungen von Softwarearchitekt:innen theorertisch und / oder praktisch zu kennen ist empfehlenswert.
Ist heile jetzt.

2024-09-11 15:34 UTC, StefanZoerner commented on docs/00b-basics/06-complementary-information.adoc
> +Die Schulung geht auf die kontextüblichen Arbeitssituationen von Architekt:innen als "Nabe im Rad" konkret ein und liefert pragmatisches Handwerkszeug, um den eigenen Soft-Skills-Baukasten anzureiche
Unsicher. Liest sich beides richtig. Ich habe mal Deine Variante gewählt, da nur NRW-Abi.

2024-09-12 07:10 UTC, programming-wolf approved these changes
Nice, danke!

2024-09-12 07:11 UTC, merged